apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: wind-turbine-pipeline-run
#  namespace: wind-turbine-race
  labels:
    tekton.dev/pipeline: wind-turbine-pipeline
spec:
  params:
    - name: IMAGE_TAG
      value: 2.0.1
    - name: IMAGE_NAME
      value: quay.io/sbergste/quinoa-wind-turbine
    - name: GIT_REPO
      value: 'https://github.com/stefan-bergstein/quinoa-wind-turbine.git'
    - name: GIT_BRANCH
      value: main
    - name: MANIFESTS_GIT_REPO
      value: 'https://github.com/stefan-bergstein/quinoa-wind-turbine-manifests.git'
    - name: MANIFESTS_GIT_BRANCH
      value: main
  pipelineRef:
    name: wind-turbine-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: app-source
    - name: maven-settings
      persistentVolumeClaim:
        claimName: build-cache-pvc
    - name: maven-repo
      persistentVolumeClaim:
        claimName: build-cache-pvc
    - name: node-cache
      persistentVolumeClaim:
        claimName: build-cache-pvc
    - name: npm-repo
      persistentVolumeClaim:
        claimName: build-cache-pvc