apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wind-turbine
  namespace: wind-turbine-race
spec:
  destination:
    namespace: wind-turbine-race
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/stefan-bergstein/quinoa-wind-turbine-manifests
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
